export default function About() {
  return (
    <div>
      <h1>About Page</h1>
      <p>
        about Atoumane! im a full stack developer, i love to code and learn new, im also multi language speaker, i speak 4 languages, i love to travel and meet new people, i love to play soccer and video games, i love to watch movies and series, i love to read books and learn new things, i love to cook and eat, i love to listen to music and dance, i love to do sports and workout, i love to spend time with my family and friends, i love to help people and make them happy, i love to make the world a better place, i love to be happy and make others happy, i love to be positive and make others positive, i love to be successful and make others successful, i love to be the best version of myself and make others the best version of themselves, i love to be me and make others be themselves, i love to be free and make others be free, i love to be love and make others be love, i love to be happy and make others be happy, i love to be me and make others be themselves, i love to be free and make others be free, i love to be love and make others be love, i love to be happy and make others be happy, i love to be me and make others be themselves, i love to be free and make others be free, i love to be love and make others be love, i love to be happy and make others be happy, i love to be me and make others be themselves, i love to be free and make others be free, i love to be love and make others be love, i love to be happy and make others be happy, i love to be me and make others be themselves, i love to be free and make others be free, i love to be love and make others be love, i love to be happy and make others be happy, i love to be me and make others be themselves, i love to be free and make others be free, i love to be love and make others be love, i love to be happy and make others be happy, i love to be me and make others be themselves, i love to be free and make others be free, i love to be love and make others be love, i love to be happy and make others be happy, i love to be me and make others be themselves, i love to be free and make others be free, i love to be love and make others be love, i love to be happy and make others be happy,
        english, french, spanish, fulani, wolof.
      </p>
    </div>
  );
}
